import type { AssetConfig, CurrencyConfig, Interval } from "./types";

export const CURRENCIES: CurrencyConfig[] = [
	{ code: "USD", symbol: "$", wsPair: "XBT/USD", locale: "en-US" },
	{ code: "EUR", symbol: "€", wsPair: "XBT/EUR", locale: "de-DE" },
	{ code: "GBP", symbol: "£", wsPair: "XBT/GBP", locale: "en-GB" },
];

export const SUPPORTED_ASSETS: AssetConfig[] = [
	{ symbol: "BTC", name: "Bitcoin", krakenId: "XBT" },
	{ symbol: "ETH", name: "Ethereum", krakenId: "ETH" },
	{ symbol: "SOL", name: "Solana", krakenId: "SOL" },
	{ symbol: "XRP", name: "XRP", krakenId: "XRP" },
	{ symbol: "BNB", name: "BNB", krakenId: "BNB" },
	{ symbol: "DOGE", name: "Dogecoin", krakenId: "XDG" },
	{ symbol: "ADA", name: "Cardano", krakenId: "ADA" },
	{ symbol: "TRX", name: "TRON", krakenId: "TRX" },
	{ symbol: "XLM", name: "Stellar", krakenId: "XLM" },
	{ symbol: "LINK", name: "Chainlink", krakenId: "LINK" },
	{ symbol: "AVAX", name: "Avalanche", krakenId: "AVAX" },
	{ symbol: "SUI", name: "Sui", krakenId: "SUI" },
	{ symbol: "DOT", name: "Polkadot", krakenId: "DOT" },
	{ symbol: "LEO", name: "LEO Token", krakenId: "LEO" },
	{ symbol: "SHIB", name: "Shiba Inu", krakenId: "SHIB" },
	{ symbol: "TON", name: "Toncoin", krakenId: "TON" },
	{ symbol: "HYPE", name: "Hyperliquid", krakenId: "HYPE" },
	{ symbol: "LTC", name: "Litecoin", krakenId: "LTC" },
	{ symbol: "BCH", name: "Bitcoin Cash", krakenId: "BCH" },
	{ symbol: "NEAR", name: "NEAR Protocol", krakenId: "NEAR" },
	{ symbol: "PEPE", name: "Pepe", krakenId: "PEPE" },
	{ symbol: "UNI", name: "Uniswap", krakenId: "UNI" },
	{ symbol: "ICP", name: "Internet Computer", krakenId: "ICP" },
	{ symbol: "POL", name: "Polygon", krakenId: "POL" },
	{ symbol: "APT", name: "Aptos", krakenId: "APT" },
	{ symbol: "HBAR", name: "Hedera", krakenId: "HBAR" },
	{ symbol: "CRO", name: "Cronos", krakenId: "CRO" },
	{ symbol: "KAS", name: "Kaspa", krakenId: "KAS" },
	{ symbol: "RENDER", name: "Render", krakenId: "RENDER" },
	{ symbol: "WLD", name: "Worldcoin", krakenId: "WLD" },
	{ symbol: "ARB", name: "Arbitrum", krakenId: "ARB" },
	{ symbol: "STX", name: "Stacks", krakenId: "STX" },
	{ symbol: "FET", name: "Fetch.ai", krakenId: "FET" },
	{ symbol: "AAVE", name: "Aave", krakenId: "AAVE" },
	{ symbol: "TIA", name: "Celestia", krakenId: "TIA" },
	{ symbol: "MKR", name: "Maker", krakenId: "MKR" },
	{ symbol: "TAO", name: "Bittensor", krakenId: "TAO" },
	{ symbol: "OKB", name: "OKB", krakenId: "OKB" },
	{ symbol: "ETC", name: "Ethereum Classic", krakenId: "ETC" },
	{ symbol: "ONDO", name: "Ondo", krakenId: "ONDO" },
	{ symbol: "FIL", name: "Filecoin", krakenId: "FIL" },
	{ symbol: "ATOM", name: "Cosmos", krakenId: "ATOM" },
	{ symbol: "SEI", name: "Sei", krakenId: "SEI" },
	{ symbol: "JUP", name: "Jupiter", krakenId: "JUP" },
	{ symbol: "FLR", name: "Flare", krakenId: "FLR" },
	{ symbol: "VET", name: "VeChain", krakenId: "VET" },
	{ symbol: "RUNE", name: "THORChain", krakenId: "RUNE" },
	{ symbol: "ENA", name: "Ethena", krakenId: "ENA" },
	{ symbol: "LDO", name: "Lido DAO", krakenId: "LDO" },
	{ symbol: "WIF", name: "dogwifhat", krakenId: "WIF" },
	{ symbol: "GRT", name: "The Graph", krakenId: "GRT" },
	{ symbol: "PYTH", name: "Pyth Network", krakenId: "PYTH" },
	{ symbol: "EOS", name: "EOS", krakenId: "EOS" },
	{ symbol: "BONK", name: "Bonk", krakenId: "BONK" },
	{ symbol: "FLOW", name: "Flow", krakenId: "FLOW" },
	{ symbol: "DYM", name: "Dymension", krakenId: "DYM" },
	{ symbol: "AKT", name: "Akash Network", krakenId: "AKT" },
	{ symbol: "PENDLE", name: "Pendle", krakenId: "PENDLE" },
	{ symbol: "STRK", name: "Starknet", krakenId: "STRK" },
	{ symbol: "BEAM", name: "Beam", krakenId: "BEAM" },
	{ symbol: "MANTA", name: "Manta Network", krakenId: "MANTA" },
	{ symbol: "NEO", name: "NEO", krakenId: "NEO" },
	{ symbol: "FTM", name: "Fantom", krakenId: "FTM" },
	{ symbol: "GALA", name: "Gala", krakenId: "GALA" },
	{ symbol: "CORE", name: "Core", krakenId: "CORE" },
	{ symbol: "RAY", name: "Raydium", krakenId: "RAY" },
	{ symbol: "EGLD", name: "MultiversX", krakenId: "EGLD" },
	{ symbol: "QNT", name: "Quant", krakenId: "QNT" },
	{ symbol: "CHZ", name: "Chiliz", krakenId: "CHZ" },
	{ symbol: "XTZ", name: "Tezos", krakenId: "XTZ" },
	{ symbol: "MANA", name: "Decentraland", krakenId: "MANA" },
	{ symbol: "SAND", name: "The Sandbox", krakenId: "SAND" },
	{ symbol: "AXS", name: "Axie Infinity", krakenId: "AXS" },
	{ symbol: "IOTA", name: "IOTA", krakenId: "IOTA" },
	{ symbol: "XMR", name: "Monero", krakenId: "XMR" },
	{ symbol: "ZEC", name: "Zcash", krakenId: "ZEC" },
	{ symbol: "AERO", name: "Aerodrome", krakenId: "AERO" },
	{ symbol: "EWT", name: "Energy Web Token", krakenId: "EWT" },
	{ symbol: "KITE", name: "Kite", krakenId: "KITE" },
	{ symbol: "NIGHT", name: "Midnight", krakenId: "NIGHT" },
	{ symbol: "VIRTUAL", name: "Virtuals Protocol", krakenId: "VIRTUAL" },
	{ symbol: "BGB", name: "Bitget Token", krakenId: "BGB" },
	{ symbol: "DYM", name: "Dymension", krakenId: "DYM" },
	{ symbol: "ALT", name: "AltLayer", krakenId: "ALT" },
	{ symbol: "RON", name: "Ronin", krakenId: "RON" },
	{ symbol: "PIXEL", name: "Pixels", krakenId: "PIXEL" },
	{ symbol: "NOT", name: "Notcoin", krakenId: "NOT" },
	{ symbol: "ZRO", name: "LayerZero", krakenId: "ZRO" },
	{ symbol: "OM", name: "Mantra", krakenId: "OM" },
	{ symbol: "JASMY", name: "JasmyCoin", krakenId: "JASMY" },
	{ symbol: "XDC", name: "XDC Network", krakenId: "XDC" },
	{ symbol: "USDE", name: "Ethena USDe", krakenId: "USDE" },
	{ symbol: "LRC", name: "Loopring", krakenId: "LRC" },
	{ symbol: "BTT", name: "BitTorrent", krakenId: "BTT" },
	{ symbol: "HOT", name: "Holo", krakenId: "HOT" },
	{ symbol: "SKY", name: "Sky", krakenId: "SKY" },
	{ symbol: "PENGU", name: "Pudgy Penguins", krakenId: "PENGU" },
	{ symbol: "MORPHO", name: "Morpho", krakenId: "MORPHO" },
	{ symbol: "BDX", name: "Beldex", krakenId: "BDX" },
	{ symbol: "GHO", name: "GHO", krakenId: "GHO" },
	{ symbol: "RAIN", name: "Rain", krakenId: "RAIN" },
	{ symbol: "COCA", name: "COCA", krakenId: "COCA" },
];

// Map asset symbol to AssetConfig
export const ASSET_MAP: Record<string, AssetConfig> = SUPPORTED_ASSETS.reduce(
	(acc, asset) => {
		acc[asset.symbol] = asset;
		return acc;
	},
	{} as Record<string, AssetConfig>,
);

export const KRAKEN_INTERVAL_MAP: Record<Interval, number> = {
	"1m": 1,
	"3m": 5,
	"5m": 5,
	"15m": 15,
	"30m": 30,
	"1h": 60,
	"2h": 240, // Fallback to 4h as Kraken doesn't support 2h
	"4h": 240,
	"12h": 1440,
	"1d": 1440,
	"3d": 10080, // Fallback to 1w as Kraken doesn't support 3d
	"1w": 10080,
	"1M": 21600,
};

export const BITGET_INTERVAL_MAP: Record<Interval, string> = {
	"1m": "1min",
	"3m": "5min",
	"5m": "5min",
	"15m": "15min",
	"30m": "30min",
	"1h": "1h",
	"2h": "1h",
	"4h": "4h",
	"12h": "12h",
	"1d": "1day",
	"3d": "1day",
	"1w": "1week",
	"1M": "1month",
};
